### ISSUE TITLE
pagarAAccionistas - Chequeo de booleanos

### ISSUE THREAD

**Issue by Maxi-F** [ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly#1]
No es necesario realizar un check `== True`! Si esto ya retorna true, el predicado es verdadero por ende pasa por esta guarda.

Ojo con estos chequeos!

https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/bffd6fada5b5133e0811b2f67cdb29563a878e72/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L143

**Comment by ERSilvaPorras** [comment]
> Buenas noches Maxi, se me paso ese check, corregido. Gracias.
> 
> https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/7f95fa0c02b33d54f6e88ea7df1b2de0cdd81d54/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L147
