### ISSUE TITLE
Funcion comentada agregarAccionQueHizo

### ISSUE THREAD

**Issue by Maxi-F** [ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly#2]
Se que igual no le debería dar importancia ya que está comentado, pero quiero comentar sobre el comment jajajajaja.

Ojo, que acciones sea una lista de funciones no implica que no puedas utilizar este mapper para cambiarlos/transformarlos a otras acciones! Si bien no se utiliza en el TP, está buena esta función!

https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/bffd6fada5b5133e0811b2f67cdb29563a878e72/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L81-L83

**Comment by ERSilvaPorras** [comment]
> jajajaja lo puse para que lo leas jaja, cuando llegue al punto donde ya era un hecho que era una lista de funciones entre en panico perdiendo de vista que como vos bien decis si el enunciado buscaba una vuelva de complejidad vendria bien. Gracias por el comentario del comentario jajaja lo mas chistoso es que yo sigo el hilo con otro comentario jaja
> 
> 
> Adjunto esta linea por que creo que apesar de que esta solucion funciona podria rescatar la funcion comentada pero me nuble y me trabe:
> https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/7f95fa0c02b33d54f6e88ea7df1b2de0cdd81d54/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L93

**Comment by Maxi-F** [comment]
Buenisimo! Queda mas expresivo el nombre tambien con esa funcionalidad!
