### ISSUE TITLE
Analizar la utilización de $ para evitar paréntesis

### ISSUE THREAD

**Issue by Maxi-F** [ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly#3]
Si bien es correcto el utilizar paréntesis, Capaz que estas funciones por ejemplo quedan mejor si aplicas el $ (O ignoras los parámetros ya que podés retornar la función compuesta 👀)

https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/bffd6fada5b5133e0811b2f67cdb29563a878e72/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L90

**Comment by ERSilvaPorras** [comment]
> En la correcion que hice en un principio para este issue lo use como me pediste pero justo  en el  issue 9 me remarcaste que se me paso agregar la funcion gritar y para solucionar este ultimo issue opte por usar composicion, gracias por el comentario soy de usar parentesis sin analizar pero en ese caso en particular ahora que recuerdo lo hice por que queria aplicar el concepto de Pointfree pero me arrepenti ya que cambie de opinion
> https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/7f95fa0c02b33d54f6e88ea7df1b2de0cdd81d54/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L90

**Comment by Maxi-F** [comment]
Perfecto!

Algo que quiero destacar es que Point Free no es un concepto, sino un "estilo" con el cual se puede programar. Esto surge por la utilización de aplicación parcial y currificación. Digo esto para no mezclar estas cosas que suele pasar en el final 👀

**Comment by ERSilvaPorras** [comment]
Gracias por la correccion, pense que era un concepto, me quedo muy claro.
