### ISSUE TITLE
subastar - Abstracción no necesaria

### ISSUE THREAD

**Issue by Maxi-F** [ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly#4]
Ojo que acá hay una abstracción no necesaria: `subastar` y `tacticasQueSubastan` realizan lo mismo. Es decir, si la lógica de `tacticasQueSubastan` estuviese toda en `subastar` sería lo mismo.

Para mejorar esto, vería de abstraer las funcionalidades internas de la función `tacticasQueSubastan` (Por ejemplo, El analisis de la tactica del jugador o tambien lo que transforma al jugador)

https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/bffd6fada5b5133e0811b2f67cdb29563a878e72/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L108-L113

**Comment by ERSilvaPorras** [comment]
>  Gracias maxi se me paso realizar ese control de ver si estaba haciendo abstracciones sin sentido para esta correcion opte por eliminar `tacticasQueSubastan` asi elimino dicha abstraccion agregando su logica dentro de `subastar`.
> 
> https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/7f95fa0c02b33d54f6e88ea7df1b2de0cdd81d54/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L109-L110
