### ISSUE TITLE
Repeticion de logica - esAccionista

### ISSUE THREAD

**Issue by Maxi-F** [ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly#5]
Ojo que hay una funcion `esAccionista` que hace lo mismo que en este chequeo en la guarda

https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/bffd6fada5b5133e0811b2f67cdb29563a878e72/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L112

**Comment by ERSilvaPorras** [comment]
> Corregido, acordate que opte por eliminar `tacticasQueSubastan`, corregi lo que me remarcaste dentro de `subastar` usando la funcion `esAccionista` que ya tenia. Gracias
> 
> https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/7f95fa0c02b33d54f6e88ea7df1b2de0cdd81d54/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L109
