### ISSUE TITLE
CasasCaras y CasasBaratas - Declaratividad

### ISSUE THREAD

**Issue by Maxi-F** [ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly#6]
Si bien es una solución correcta para obtener las casas baratas y las casas caras, me parece que le falta declaratividad a esto, más que nada a `casasCarasDe`.

En una primera leida, lo que veo en esa función es "Las casas caras de un jugador son la cantidad de propiedades que tiene el jugador menos las casas baratas que tiene el jugador". Si bien es correcta esta preposición, no sería mejor si de primera leida veo "Las casas caras del jugador son las que valen más de 150", como dice el enunciado?

Ojo, esto lo dejo abierto a discusión, es difícil de ver ya que entiendo que la función queda así para no repetir lógica con `casasBaratasDe` (Disclaimer: Hay una manera para no repetir lógica y que quede de primera leida como el parrafo anterior 👀)

https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/bffd6fada5b5133e0811b2f67cdb29563a878e72/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L129-L133

**Comment by ERSilvaPorras** [comment]
> Creo que entendi tu mensaje jajaja te adjunto mi solucion que creo que es declarativa. Gracias. En caso de que haya una mejor forma te agradeceria que me indiques un ejemplo por favor.

> PD: no me gusto poner delante como primer parametro al jugador sera mi TOC no se sabe jaja lo hice para que el nombre de la funcion sea entendible con base en el orden de los parametros a pedir.
 
> https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/7f95fa0c02b33d54f6e88ea7df1b2de0cdd81d54/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L129-L133

**Comment by Maxi-F** [comment]
Genial!

Si cambiás el orden de los parametros en `casasDeJugadorQueCumpleCondicion` como indicaste en la posdata, podrías retornar las funciones `casasDeJugadorQueCumpleCondicion (>150)` y `casasDeJugadorqueCumpleCondicion (<=150)`
