### ISSUE TITLE
hacerBerrinchePor - Parentesis innecesarios

### ISSUE THREAD

**Issue by Maxi-F** [ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly#7]
No son necesarios los paréntesis en gritar

https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/bffd6fada5b5133e0811b2f67cdb29563a878e72/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L160

**Comment by ERSilvaPorras** [comment]
Perdon Maxi me pueden los parentesis 👎🏼, es un TOC por ver cada funcion mas legible para que se destaque mejor la composicion. Gracias.

> https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/7f95fa0c02b33d54f6e88ea7df1b2de0cdd81d54/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L164
