### ISSUE TITLE
Juego final

### ISSUE THREAD

**Issue by Maxi-F** [ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly#8]
Ojo con los retornos de strings. Si bien está bueno para verlo en la consola, lo que era necesario es retornar al jugador.

Puede parecer rara esta corrección, pero está bueno dividir lo que es la parte lógica con la parte de presentación. Por ejemplo, si se pidiera modificar las acciones del jugador ganador de la ronda, ¿Lo podría hacer con esta función?

Lo que sí se podría realizar es una función que retorne un String mostrando quién es el jugador ganador, para mostrarlo en pantalla, y esta función es la que se utiliza de manera de "presentación" en consola (no es pedida en el TP pero a modo de ejemplo)

https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/bffd6fada5b5133e0811b2f67cdb29563a878e72/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L181-L185

**Comment by ERSilvaPorras** [comment]
Si suelo cometer el error de priorizar la presentacion, gracias por remarcarme eso. Lo quise hacer ya que en el caso de empate no sabia como solucionar ese resultado pero como es `juegoFinal`l  te argumento que meditandolo mejor forzadamente yo quiero un ganador y no tengo en consideracion un empate.

PD: Se puede imprimir dos jugadores como resultado de una funcion?

> https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/7f95fa0c02b33d54f6e88ea7df1b2de0cdd81d54/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L185-L188

**Comment by Maxi-F** [comment]
Mmmm se podría armar una función que tome dos jugadores y arme un string para retornar los nombres de ambos se me ocurre... Igualmente es capa de presentacion!

**Comment by ERSilvaPorras** [comment]
Claro tenia eso en mente. Gracias por el consejo.
