### ISSUE TITLE
Enojarse - Falta agregar gritar a sus acciones

### ISSUE THREAD

**Issue by Maxi-F** [ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly#9]
https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/bffd6fada5b5133e0811b2f67cdb29563a878e72/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L89-L90

**Comment by ERSilvaPorras** [comment]
Por fin llegue al utlimo issue jajaja no sabes lo que me costo imitar la forma en como se adjunta el codigo, me tomo el atrevimiento de pedirte si me pudieras enseñar un poco este mundo de los issues mas que nada adjuntar codigo rapido, quise en issues anteriores adjuntar nombres de issues y no pude. Gracias por las correcciones muy claras.


Correccion indicada: 
> https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/7f95fa0c02b33d54f6e88ea7df1b2de0cdd81d54/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L89-L90

>
>
>
>
>
>
PD: Una ultima consulta, te indico la linea donde me surgio una duda que la comente

> https://github.com/ERSilvaPorras/PDO-TP-FUNCIONAL-monopoly/blob/7f95fa0c02b33d54f6e88ea7df1b2de0cdd81d54/PDP-TP-INDIVIDUAL-monopoly-VF.hs#L173

**Comment by Maxi-F** [comment]
Genial!

Por sobre los issues, te dejo un gif de tutorial de cómo los referencio:

![Copy-lines](https://user-images.githubusercontent.com/21026390/119243278-a58edd00-bb3b-11eb-9050-244be06f1d82.gif)
> Nota: Cuando selecciono la linea 165, lo hago manteniendo la tecla `shift`. Cuando toqué `Copy Permalink` lo que hace es hacerte un link con el codigo para referenciarlo, y después con `ctrl + v` podés pegar ese link en el issue y queda copiado.

Sobre la consulta, la verdad no sé si se puede imprimir la función completa más que `<function>`. Averiguo y te cuento!

**Comment by ERSilvaPorras** [comment]
Muchas gracias por su tiempo para las correcciones, me ayudaron mucho sobre todo en que debo estar mas atento a la hora controlar la repeticion de logica y expresividad en los nombres de las funciones. Mil gracias por el asunto de los issues se que son cosas que exeden a los temas de la materia.
